[app]
print_every_min = 5

[message]
[[message.feishu]]
channel = "signal"
webhook = "https://open.feishu.cn/open-apis/bot/v2/hook/17914dc0-0523-4ed1-a62e-4d5c6e3b8654"
secret = "33659DAUg2Q3Ac6BjnSOOc"
[[message.feishu]]
channel = "order"
webhook = "https://open.feishu.cn/open-apis/bot/v2/hook/cd1d71df-0e0d-41d2-8051-e42acd078bc6"
secret = "3OdMwaB0CNMmiuW9UY4qWb"
[[message.feishu]]
channel = "pnl"
webhook = "https://open.feishu.cn/open-apis/bot/v2/hook/0ef4258e-e6bb-4772-9fce-190e15aba3b1"
secret = "V6B6RfaYBbxS4SopH92Xlb"
[[message.feishu]]
channel = "market"
webhook = "https://open.feishu.cn/open-apis/bot/v2/hook/5e3917f8-14de-4855-a9bb-ba197ac9dcb5"
secret = "PjeS66quKWulErS9l4XCde"

[symbols]
# base
coins = ["BTC", "ETH", "SOL"]
quote = "USDT"

[arbitrage]
delta_threshold = 5.0

# [monitor] 部分用于配置监控设置
# exchanges: 要监控的交易所列表，用于两两比较跨交易所的套利机会
# 如果留空，将自动监控所有启用的交易所
# 注意：只有enabled=true的交易所才会被实际监控
[monitor]
# 例如在binance/bybit/okx之间监控套利机会
# exchanges = ["binance", "bybit", "okx"]
# 如果留空，则自动使用所有enabled的交易所
exchanges = []

[exchanges.binance]
enabled = false
api_key = "GODOZ5H4IQVahtXu216X5kdQBTbYT4tNf5LydQWuxexlMJZrw0xbQvrL1BP1PunN"
secret_key = "j14JDmShOc6SUppf6Uz4vhnQwsbUGK6f2NzfTV4hGcnkwCJaXq8OtNbZUx5gLINU"
[exchanges.binance.spot]
enabled = true
http = "https://api.binance.com"
ws = "wss://stream.binance.com:443/ws"
[exchanges.binance.perpetual]
enabled = true
http = "https://fapi.binance.com"
ws = "wss://fstream.binance.com/ws"


[exchanges.bybit]
enabled = true
api_key = "ovxG4pT6BFE8Oh7b7E"
secret_key = "gPfgyDrfR4WswFdPgVpXsbnSEQeaCcX30Lsu"
[exchanges.bybit.spot]
enabled = false
http = "https://api.bybit.com"
ws = "wss://stream.bybit.com/v5/public/spot"
[exchanges.bybit.perpetual]
enabled = true
http = "https://api.bybit.com"
ws = "wss://stream.bybit.com/v5/public/linear"

[exchanges.okx]
enabled = true
api_key = "dc6a2205-830f-4952-9acd-81d5b9ea2470"
secret_key = "6218E25764E121957B36D854B4776FEC"
passphrase = "Trade123@"
[exchanges.okx.spot]
enabled = false
http = "https://www.okx.com"
ws = "wss://ws.okx.com:8443/ws/v5/public"
[exchanges.okx.perpetual]
enabled = true
http = "https://www.okx.com"
ws = "wss://ws.okx.com:8443/ws/v5/public"

[exchanges.bitget]
enabled = false
api_key = "bg_6fe0bc583114ca91cb35c4c5a33b1c3d"
secret_key = "50ec0bdaaa0d43e301fdf286029da7029b5d33dedd412d60e408c88624484710"
passphrase = "Box2024btc"
[exchanges.bitget.spot]
enabled = false
http = "https://api.bitget.com"
ws = "wss://ws.bitget.com/v2/ws/public"
[exchanges.bitget.perpetual]
enabled = false
http = "https://api.bitget.com"
ws = "wss://ws.bitget.com/v2/ws/public"

[redis]
enabled = true
addr = "127.0.0.1:6379"
password = "foobared"
db = 0
ttl_seconds = 60
prefix = "xarb"
signal_stream = "xarb:signals"
signal_channel = "xarb:signals:pub"

# [postgres]
# enabled = false
# dsn = "postgres://user:pass@127.0.0.1:5432/xarb?sslmode=disable"

[sqlite]
enabled = true
path = "./data/xarb.db"
